import type { AppData, UserRole, UserSession } from './models'

export const roleSessions: Record<UserRole, UserSession> = {
  farmer: { role: 'farmer', name: '绿丰生态养殖场', homePath: '/farmer/origin-apply' },
  vet: { role: 'vet', name: '官方兽医 王敏', homePath: '/vet/origin-todos' },
  slaughter: { role: 'slaughter', name: '皖北标准化屠宰中心', homePath: '/slaughter/entry-check' },
  regulator: { role: 'regulator', name: '市级畜牧兽医监管员', homePath: '/regulator/dashboard' },
}

export function createSeedData(): AppData {
  return {
    farmBatches: [
      {
        id: 'batch-001',
        farmName: '绿丰生态养殖场',
        animalType: '生猪',
        breed: '杜长大三元猪',
        stock: 320,
        immuneQualified: true,
        earTagPrefix: 'AH-LF-2026',
        earTagStart: 1001,
        earTagEnd: 1320,
        location: '安徽省阜阳市颍州区三十里铺镇',
      },
      {
        id: 'batch-002',
        farmName: '青禾家庭农场',
        animalType: '肉牛',
        breed: '西门塔尔牛',
        stock: 86,
        immuneQualified: true,
        earTagPrefix: 'AH-QH-2026',
        earTagStart: 2201,
        earTagEnd: 2286,
        location: '安徽省亳州市涡阳县楚店镇',
      },
      {
        id: 'batch-003',
        farmName: '双河合作社',
        animalType: '羊',
        breed: '湖羊',
        stock: 180,
        immuneQualified: false,
        earTagPrefix: 'AH-SH-2026',
        earTagStart: 3101,
        earTagEnd: 3280,
        location: '安徽省宿州市埇桥区栏杆镇',
      },
    ],
    vehicles: [
      {
        id: 'vehicle-001',
        plateNo: '皖K·A3189',
        carrier: '李建国',
        registered: true,
        blacklisted: false,
        channel: '东门动物运输专用通道',
      },
      {
        id: 'vehicle-002',
        plateNo: '皖S·P7726',
        carrier: '张长运',
        registered: true,
        blacklisted: false,
        channel: '北门临检通道',
      },
      {
        id: 'vehicle-003',
        plateNo: '皖A·X4091',
        carrier: '刘某',
        registered: false,
        blacklisted: true,
        channel: '东门动物运输专用通道',
      },
    ],
    originApplications: [],
    quarantineCertificates: [],
    transportTasks: [],
    landingReports: [],
    carrierRestrictions: [],
    entryChecks: [],
    slaughterApplications: [],
    waitingSlaughterBatches: [],
    anteMortemChecks: [],
    postMortemChecks: [],
    productCertificates: [],
    meatQualityCertificates: [],
    threeCertificateLinks: [],
    harmlessTasks: [],
    sealRecords: [
      {
        id: 'seal-seed-001',
        sealNo: 'QYBZ-2026-0001',
        action: 'receive',
        quantity: 500,
        operator: '证章管理员',
        createdAt: new Date().toISOString(),
      },
    ],
    syncLogs: [],
    closedLoopNodes: [],
    operationLogs: [],
    alerts: [],
  }
}
